version: '3.8'

services:
  backend:
    build: ./backend
    container_name: whatsapp-pairing-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./sessions:/app/sessions
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: whatsapp-pairing-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sessions: